version: 0.2

phases:
  install:
    commands:
      - wget -O ./cxcli.tar.gz "https://github.com/Checkmarx/ast-cli/releases/download/2.2.5/ast-cli_2.2.5_linux_x64.tar.gz"
      - tar xzvf ./cxcli.tar.gz
  build:
    commands:
      - ./cx scan create --project-name "Rishav_AWS_CodeBuild" --file-source "." --branch "main" --report-format 'summaryHTML' --agent 'CodeCommit' --base-uri "https://eu.ast.checkmarx.net" --tenant "dp_wp_account" --client-id "$CX_CLIENT_ID" --client-secret "$CX_CLIENT_SECRET" --debug
